version: '3.1'

services:
  db:
    image: postgres
    restart: always
    # ports: 
    #   - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: codegig  
    volumes:
      - ./pg-data/data:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  web:
    build: "."
    restart: always
    command: npm run dev
    ports:
      - 3000:3000
    environment:
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    volumes: 
      - .:/usr/src/app
    links:
      - db
      - adminer
  
